import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import { getServerSession } from "@/lib/get-session";
import { redirect } from "next/navigation";
import AuthNavbar from "./auth-navbar";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const session = await getServerSession()
  const user = session?.user

  if(user) redirect("/dashboard")

  return (
    <html lang="en">
      <body
        className=''
      >
        <AuthNavbar />
        {children}
      </body>
    </html>
  );
}
